"""init schema with v2 topic mining tables

Revision ID: 155a29b4aa94
Revises: 
Create Date: 2026-05-21 10:24:37.574596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '155a29b4aa94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_topic_lists',
    sa.Column('list_date', sa.Date(), nullable=False),
    sa.Column('top_n', sa.Integer(), nullable=True),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('direction_distribution', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_topic_lists_id'), 'daily_topic_lists', ['id'], unique=False)
    op.create_index(op.f('ix_daily_topic_lists_list_date'), 'daily_topic_lists', ['list_date'], unique=True)
    op.create_table('info_clusters',
    sa.Column('core_title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('info_type', sa.String(length=30), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('elements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('source_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('freshness', sa.String(length=20), nullable=True),
    sa.Column('heat_score', sa.Float(), nullable=True),
    sa.Column('low_fan_hit', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('mined', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_direction_heat', 'info_clusters', ['direction', 'heat_score'], unique=False)
    op.create_index('ix_cluster_mined_freshness', 'info_clusters', ['mined', 'freshness'], unique=False)
    op.create_index(op.f('ix_info_clusters_direction'), 'info_clusters', ['direction'], unique=False)
    op.create_index(op.f('ix_info_clusters_freshness'), 'info_clusters', ['freshness'], unique=False)
    op.create_index(op.f('ix_info_clusters_heat_score'), 'info_clusters', ['heat_score'], unique=False)
    op.create_index(op.f('ix_info_clusters_id'), 'info_clusters', ['id'], unique=False)
    op.create_index(op.f('ix_info_clusters_info_type'), 'info_clusters', ['info_type'], unique=False)
    op.create_index(op.f('ix_info_clusters_mined'), 'info_clusters', ['mined'], unique=False)
    op.create_table('source_registry',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('direction_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('auth_status', sa.String(length=20), nullable=True),
    sa.Column('fetch_strategy', sa.String(length=20), nullable=True),
    sa.Column('fetch_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_registry_enabled'), 'source_registry', ['enabled'], unique=False)
    op.create_index(op.f('ix_source_registry_id'), 'source_registry', ['id'], unique=False)
    op.create_index(op.f('ix_source_registry_name'), 'source_registry', ['name'], unique=False)
    op.create_index(op.f('ix_source_registry_platform'), 'source_registry', ['platform'], unique=True)
    op.create_index(op.f('ix_source_registry_source_type'), 'source_registry', ['source_type'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('heat_score', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('articles_for_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_for_analysis_id'), 'articles_for_analysis', ['id'], unique=False)
    op.create_table('source_accounts',
    sa.Column('source_registry_id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('verified', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('suitable_for', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('fans_count', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_registry_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_registry_id', 'handle', 'display_name', name='uq_account_per_source')
    )
    op.create_index('ix_account_priority', 'source_accounts', ['priority'], unique=False)
    op.create_index(op.f('ix_source_accounts_enabled'), 'source_accounts', ['enabled'], unique=False)
    op.create_index(op.f('ix_source_accounts_handle'), 'source_accounts', ['handle'], unique=False)
    op.create_index(op.f('ix_source_accounts_id'), 'source_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_source_accounts_source_registry_id'), 'source_accounts', ['source_registry_id'], unique=False)
    op.create_table('style_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('style_features', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('language_style', sa.String(length=100), nullable=True),
    sa.Column('sentence_structure', sa.String(length=100), nullable=True),
    sa.Column('vocabulary_level', sa.String(length=100), nullable=True),
    sa.Column('paragraph_length', sa.String(length=100), nullable=True),
    sa.Column('use_emoji', sa.Boolean(), nullable=True),
    sa.Column('use_questions', sa.Boolean(), nullable=True),
    sa.Column('use_statistics', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_profiles_id'), 'style_profiles', ['id'], unique=False)
    op.create_table('topic_candidates',
    sa.Column('info_cluster_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('routine', sa.String(length=200), nullable=True),
    sa.Column('dimension_combo', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('value_promise', sa.Text(), nullable=True),
    sa.Column('angle_note', sa.Text(), nullable=True),
    sa.Column('persona_divergence', sa.Float(), nullable=True),
    sa.Column('persona_divergence_flag', sa.Boolean(), nullable=True),
    sa.Column('veto_passed', sa.Boolean(), nullable=True),
    sa.Column('veto_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['info_cluster_id'], ['info_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_direction_score', 'topic_candidates', ['direction', 'weighted_score'], unique=False)
    op.create_index('ix_candidate_verdict_score', 'topic_candidates', ['verdict', 'weighted_score'], unique=False)
    op.create_index(op.f('ix_topic_candidates_direction'), 'topic_candidates', ['direction'], unique=False)
    op.create_index(op.f('ix_topic_candidates_id'), 'topic_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_topic_candidates_info_cluster_id'), 'topic_candidates', ['info_cluster_id'], unique=False)
    op.create_index(op.f('ix_topic_candidates_persona_divergence_flag'), 'topic_candidates', ['persona_divergence_flag'], unique=False)
    op.create_index(op.f('ix_topic_candidates_verdict'), 'topic_candidates', ['verdict'], unique=False)
    op.create_index(op.f('ix_topic_candidates_veto_passed'), 'topic_candidates', ['veto_passed'], unique=False)
    op.create_index(op.f('ix_topic_candidates_weighted_score'), 'topic_candidates', ['weighted_score'], unique=False)
    op.create_table('topic_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_collections_id'), 'topic_collections', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('wechat_id', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.String(length=200), nullable=True),
    sa.Column('content_style', sa.String(length=200), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('candidate_scores',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('pain_point', sa.Float(), nullable=False),
    sa.Column('value_density', sa.Float(), nullable=False),
    sa.Column('propagation', sa.Float(), nullable=False),
    sa.Column('differentiation', sa.Float(), nullable=False),
    sa.Column('freshness', sa.Float(), nullable=False),
    sa.Column('audience_fit', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['topic_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_scores_candidate_id'), 'candidate_scores', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_candidate_scores_id'), 'candidate_scores', ['id'], unique=False)
    op.create_table('content_creations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('style_profile_id', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('reading_time', sa.Integer(), nullable=True),
    sa.Column('featured_image', sa.String(length=1000), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_platform', sa.String(length=50), nullable=True),
    sa.Column('platform_url', sa.String(length=1000), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['style_profile_id'], ['style_profiles.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_creations_id'), 'content_creations', ['id'], unique=False)
    op.create_table('daily_topic_list_items',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score_snapshot', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['topic_candidates.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['daily_topic_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_topic_list_items_candidate_id'), 'daily_topic_list_items', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_daily_topic_list_items_id'), 'daily_topic_list_items', ['id'], unique=False)
    op.create_index(op.f('ix_daily_topic_list_items_list_id'), 'daily_topic_list_items', ['list_id'], unique=False)
    op.create_table('persona_reviews',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['topic_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_reviews_candidate_id'), 'persona_reviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_persona_reviews_id'), 'persona_reviews', ['id'], unique=False)
    op.create_table('raw_infos',
    sa.Column('source_registry_id', sa.Integer(), nullable=False),
    sa.Column('source_account_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('engagement', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('extras', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('info_cluster_id', sa.Integer(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['info_cluster_id'], ['info_clusters.id'], ),
    sa.ForeignKeyConstraint(['source_account_id'], ['source_accounts.id'], ),
    sa.ForeignKeyConstraint(['source_registry_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_info_source_published', 'raw_infos', ['source_registry_id', 'published_at'], unique=False)
    op.create_index('ix_raw_info_state_scraped', 'raw_infos', ['state', 'scraped_at'], unique=False)
    op.create_index(op.f('ix_raw_infos_dedup_hash'), 'raw_infos', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_raw_infos_id'), 'raw_infos', ['id'], unique=False)
    op.create_index(op.f('ix_raw_infos_info_cluster_id'), 'raw_infos', ['info_cluster_id'], unique=False)
    op.create_index(op.f('ix_raw_infos_published_at'), 'raw_infos', ['published_at'], unique=False)
    op.create_index(op.f('ix_raw_infos_scraped_at'), 'raw_infos', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_raw_infos_source_account_id'), 'raw_infos', ['source_account_id'], unique=False)
    op.create_index(op.f('ix_raw_infos_source_registry_id'), 'raw_infos', ['source_registry_id'], unique=False)
    op.create_index(op.f('ix_raw_infos_state'), 'raw_infos', ['state'], unique=False)
    op.create_index(op.f('ix_raw_infos_url'), 'raw_infos', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_infos_url'), table_name='raw_infos')
    op.drop_index(op.f('ix_raw_infos_state'), table_name='raw_infos')
    op.drop_index(op.f('ix_raw_infos_source_registry_id'), table_name='raw_infos')
    op.drop_index(op.f('ix_raw_infos_source_account_id'), table_name='raw_infos')
    op.drop_index(op.f('ix_raw_infos_scraped_at'), table_name='raw_infos')
    op.drop_index(op.f('ix_raw_infos_published_at'), table_name='raw_infos')
    op.drop_index(op.f('ix_raw_infos_info_cluster_id'), table_name='raw_infos')
    op.drop_index(op.f('ix_raw_infos_id'), table_name='raw_infos')
    op.drop_index(op.f('ix_raw_infos_dedup_hash'), table_name='raw_infos')
    op.drop_index('ix_raw_info_state_scraped', table_name='raw_infos')
    op.drop_index('ix_raw_info_source_published', table_name='raw_infos')
    op.drop_table('raw_infos')
    op.drop_index(op.f('ix_persona_reviews_id'), table_name='persona_reviews')
    op.drop_index(op.f('ix_persona_reviews_candidate_id'), table_name='persona_reviews')
    op.drop_table('persona_reviews')
    op.drop_index(op.f('ix_daily_topic_list_items_list_id'), table_name='daily_topic_list_items')
    op.drop_index(op.f('ix_daily_topic_list_items_id'), table_name='daily_topic_list_items')
    op.drop_index(op.f('ix_daily_topic_list_items_candidate_id'), table_name='daily_topic_list_items')
    op.drop_table('daily_topic_list_items')
    op.drop_index(op.f('ix_content_creations_id'), table_name='content_creations')
    op.drop_table('content_creations')
    op.drop_index(op.f('ix_candidate_scores_id'), table_name='candidate_scores')
    op.drop_index(op.f('ix_candidate_scores_candidate_id'), table_name='candidate_scores')
    op.drop_table('candidate_scores')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_topic_collections_id'), table_name='topic_collections')
    op.drop_table('topic_collections')
    op.drop_index(op.f('ix_topic_candidates_weighted_score'), table_name='topic_candidates')
    op.drop_index(op.f('ix_topic_candidates_veto_passed'), table_name='topic_candidates')
    op.drop_index(op.f('ix_topic_candidates_verdict'), table_name='topic_candidates')
    op.drop_index(op.f('ix_topic_candidates_persona_divergence_flag'), table_name='topic_candidates')
    op.drop_index(op.f('ix_topic_candidates_info_cluster_id'), table_name='topic_candidates')
    op.drop_index(op.f('ix_topic_candidates_id'), table_name='topic_candidates')
    op.drop_index(op.f('ix_topic_candidates_direction'), table_name='topic_candidates')
    op.drop_index('ix_candidate_verdict_score', table_name='topic_candidates')
    op.drop_index('ix_candidate_direction_score', table_name='topic_candidates')
    op.drop_table('topic_candidates')
    op.drop_index(op.f('ix_style_profiles_id'), table_name='style_profiles')
    op.drop_table('style_profiles')
    op.drop_index(op.f('ix_source_accounts_source_registry_id'), table_name='source_accounts')
    op.drop_index(op.f('ix_source_accounts_id'), table_name='source_accounts')
    op.drop_index(op.f('ix_source_accounts_handle'), table_name='source_accounts')
    op.drop_index(op.f('ix_source_accounts_enabled'), table_name='source_accounts')
    op.drop_index('ix_account_priority', table_name='source_accounts')
    op.drop_table('source_accounts')
    op.drop_index(op.f('ix_articles_for_analysis_id'), table_name='articles_for_analysis')
    op.drop_table('articles_for_analysis')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_source_registry_source_type'), table_name='source_registry')
    op.drop_index(op.f('ix_source_registry_platform'), table_name='source_registry')
    op.drop_index(op.f('ix_source_registry_name'), table_name='source_registry')
    op.drop_index(op.f('ix_source_registry_id'), table_name='source_registry')
    op.drop_index(op.f('ix_source_registry_enabled'), table_name='source_registry')
    op.drop_table('source_registry')
    op.drop_index(op.f('ix_info_clusters_mined'), table_name='info_clusters')
    op.drop_index(op.f('ix_info_clusters_info_type'), table_name='info_clusters')
    op.drop_index(op.f('ix_info_clusters_id'), table_name='info_clusters')
    op.drop_index(op.f('ix_info_clusters_heat_score'), table_name='info_clusters')
    op.drop_index(op.f('ix_info_clusters_freshness'), table_name='info_clusters')
    op.drop_index(op.f('ix_info_clusters_direction'), table_name='info_clusters')
    op.drop_index('ix_cluster_mined_freshness', table_name='info_clusters')
    op.drop_index('ix_cluster_direction_heat', table_name='info_clusters')
    op.drop_table('info_clusters')
    op.drop_index(op.f('ix_daily_topic_lists_list_date'), table_name='daily_topic_lists')
    op.drop_index(op.f('ix_daily_topic_lists_id'), table_name='daily_topic_lists')
    op.drop_table('daily_topic_lists')
    # ### end Alembic commands ###
