"""add embedding vector columns

Revision ID: b1e38652277b
Revises: 155a29b4aa94
Create Date: 2026-05-21 10:31:09.176518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b1e38652277b'
down_revision: Union[str, None] = '155a29b4aa94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_clusters', sa.Column('centroid', pgvector.sqlalchemy.Vector(dim=1024), nullable=True))
    op.add_column('raw_infos', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_infos', 'embedding')
    op.drop_column('info_clusters', 'centroid')
    # ### end Alembic commands ###
