"""add business_sensitive on topic_candidate

Revision ID: e55bc58b6a7b
Revises: 20260522_add_outline_tables
Create Date: 2026-05-22 15:34:55.580577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55bc58b6a7b'
down_revision: Union[str, None] = '20260522_add_outline_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_creations', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.add_column('content_creations', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.add_column('content_creations', sa.Column('outline_id', sa.Integer(), nullable=True))
    op.add_column('content_creations', sa.Column('title_task_id', sa.String(length=100), nullable=True))
    op.add_column('content_creations', sa.Column('content_task_id', sa.String(length=100), nullable=True))
    op.add_column('content_creations', sa.Column('outline_status', sa.String(length=20), nullable=True))
    op.add_column('content_creations', sa.Column('title_status', sa.String(length=20), nullable=True))
    op.add_column('content_creations', sa.Column('content_status', sa.String(length=20), nullable=True))
    op.add_column('content_creations', sa.Column('topic_title', sa.String(length=500), nullable=True))
    op.add_column('content_creations', sa.Column('topic_direction', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'content_creations', 'topic_candidates', ['candidate_id'], ['id'])
    op.create_foreign_key(None, 'content_creations', 'outlines', ['outline_id'], ['id'])
    op.create_foreign_key(None, 'content_creations', 'info_clusters', ['cluster_id'], ['id'])
    op.add_column('topic_candidates', sa.Column('business_sensitive', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_topic_candidates_business_sensitive'), 'topic_candidates', ['business_sensitive'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_candidates_business_sensitive'), table_name='topic_candidates')
    op.drop_column('topic_candidates', 'business_sensitive')
    op.drop_constraint(None, 'content_creations', type_='foreignkey')
    op.drop_constraint(None, 'content_creations', type_='foreignkey')
    op.drop_constraint(None, 'content_creations', type_='foreignkey')
    op.drop_column('content_creations', 'topic_direction')
    op.drop_column('content_creations', 'topic_title')
    op.drop_column('content_creations', 'content_status')
    op.drop_column('content_creations', 'title_status')
    op.drop_column('content_creations', 'outline_status')
    op.drop_column('content_creations', 'content_task_id')
    op.drop_column('content_creations', 'title_task_id')
    op.drop_column('content_creations', 'outline_id')
    op.drop_column('content_creations', 'cluster_id')
    op.drop_column('content_creations', 'candidate_id')
    # ### end Alembic commands ###
