"""add zh translation fields on info_cluster

Revision ID: fff298cde66a
Revises: b1e38652277b
Create Date: 2026-05-22 10:00:45.848218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff298cde66a'
down_revision: Union[str, None] = 'b1e38652277b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_clusters', sa.Column('core_title_zh', sa.String(length=500), nullable=True))
    op.add_column('info_clusters', sa.Column('summary_zh', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_clusters', 'summary_zh')
    op.drop_column('info_clusters', 'core_title_zh')
    # ### end Alembic commands ###
